language: node_js
node_js:
  - "0.10"
before_install: npm install -g grunt-cli
install: npm install
before_script: createuser postgres_starter_test --createdb; createdb postgres_starter_test -O postgres_starter_test;
after_script: dropdb postgres_starter_test; dropuser postgres_starter_test;
